---
.travis.yml:
  secure: "xUIeRGNZrIjPoNNZYTT+pqscseiBX8ZflGmXqxvn715j/LQe6Zf0fDvHYvsMvjN1HNqLHGBNfshPSIwyuHzcNhvZ59Rx6O4vJh/+0UdxYQ8314bzUh6tjF8MheuTqnmOx89JKa0Zpie+5fF61rE2vBztriFGiyVZIn1JeSTOUdX7ie9eGad805h+Vv0a4tkXjVDQ42QFvdAnbwfWT3u/Uwjq5UnoR2jVPSmEH70qJTveFDuTX2aTA2de0bJF+U6aeoFPPPyY6Z/OvPx+mtEN0BvO4D2jx+XMPn0+czbOoYOf9GYxD5NFf3+C2gP4wPEfmF8T02E0h8jPFtCU7yOYVGqmcQoulOo2MtqR15K3DiVv4hX5HICfRkPB+1sbjo2tVrXTjVbu6UeErvoRKQVyTV+N+K5M7RKDP4TU0ayBdBlI+qPO1moMXl5KwXMifMH0k6eCfy1syVskVtyJ7dmOjBV80C99CJVeb4EU9tCc+gxEceGAtFTS6mprWIQp3bgRT36TTSv03rZNQQCtGCJdqjEeQApPLkmDb1cGxqW0pwVn7XPqLpJUoVQs6nbKoCsqzv63LzWI7c4d6HBHdqJ6guDHnGaSb6EiXhhLk5o8lFq1QpSHRH7di9X84JGb3DX8mpS77zo4MqGNJ2Lv6VAVPNQJI37qu3ghU6UKI5IdCPo="
spec/spec_helper_acceptance.rb:
  unmanaged: false
Gemfile:
  optional:
    ':test':
      - gem: puppet-lint-param-docs
